//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class ErrorRecoveryGoal : Message
    {
        public const string k_RosMessageName = "franka_msgs/ErrorRecovery";
        public override string RosMessageName => k_RosMessageName;


        public ErrorRecoveryGoal()
        {
        }
        public static ErrorRecoveryGoal Deserialize(MessageDeserializer deserializer) => new ErrorRecoveryGoal(deserializer);

        private ErrorRecoveryGoal(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ErrorRecoveryGoal: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
