//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class ErrorRecoveryFeedback : Message
    {
        public const string k_RosMessageName = "franka_msgs/ErrorRecovery";
        public override string RosMessageName => k_RosMessageName;


        public ErrorRecoveryFeedback()
        {
        }
        public static ErrorRecoveryFeedback Deserialize(MessageDeserializer deserializer) => new ErrorRecoveryFeedback(deserializer);

        private ErrorRecoveryFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ErrorRecoveryFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
