//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class ErrorRecoveryResult : Message
    {
        public const string k_RosMessageName = "franka_msgs/ErrorRecovery";
        public override string RosMessageName => k_RosMessageName;


        public ErrorRecoveryResult()
        {
        }
        public static ErrorRecoveryResult Deserialize(MessageDeserializer deserializer) => new ErrorRecoveryResult(deserializer);

        private ErrorRecoveryResult(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ErrorRecoveryResult: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
