//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetCartesianImpedanceRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetCartesianImpedance";
        public override string RosMessageName => k_RosMessageName;

        public double[] cartesian_stiffness;

        public SetCartesianImpedanceRequest()
        {
            this.cartesian_stiffness = new double[6];
        }

        public SetCartesianImpedanceRequest(double[] cartesian_stiffness)
        {
            this.cartesian_stiffness = cartesian_stiffness;
        }

        public static SetCartesianImpedanceRequest Deserialize(MessageDeserializer deserializer) => new SetCartesianImpedanceRequest(deserializer);

        private SetCartesianImpedanceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cartesian_stiffness, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cartesian_stiffness);
        }

        public override string ToString()
        {
            return "SetCartesianImpedanceRequest: " +
            "\ncartesian_stiffness: " + System.String.Join(", ", cartesian_stiffness.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
