//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetEEFrameRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetEEFrame";
        public override string RosMessageName => k_RosMessageName;

        public double[] NE_T_EE;

        public SetEEFrameRequest()
        {
            this.NE_T_EE = new double[16];
        }

        public SetEEFrameRequest(double[] NE_T_EE)
        {
            this.NE_T_EE = NE_T_EE;
        }

        public static SetEEFrameRequest Deserialize(MessageDeserializer deserializer) => new SetEEFrameRequest(deserializer);

        private SetEEFrameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.NE_T_EE, sizeof(double), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.NE_T_EE);
        }

        public override string ToString()
        {
            return "SetEEFrameRequest: " +
            "\nNE_T_EE: " + System.String.Join(", ", NE_T_EE.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
