//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetFullCollisionBehaviorRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetFullCollisionBehavior";
        public override string RosMessageName => k_RosMessageName;

        public double[] lower_torque_thresholds_acceleration;
        public double[] upper_torque_thresholds_acceleration;
        public double[] lower_torque_thresholds_nominal;
        public double[] upper_torque_thresholds_nominal;
        public double[] lower_force_thresholds_acceleration;
        public double[] upper_force_thresholds_acceleration;
        public double[] lower_force_thresholds_nominal;
        public double[] upper_force_thresholds_nominal;

        public SetFullCollisionBehaviorRequest()
        {
            this.lower_torque_thresholds_acceleration = new double[7];
            this.upper_torque_thresholds_acceleration = new double[7];
            this.lower_torque_thresholds_nominal = new double[7];
            this.upper_torque_thresholds_nominal = new double[7];
            this.lower_force_thresholds_acceleration = new double[6];
            this.upper_force_thresholds_acceleration = new double[6];
            this.lower_force_thresholds_nominal = new double[6];
            this.upper_force_thresholds_nominal = new double[6];
        }

        public SetFullCollisionBehaviorRequest(double[] lower_torque_thresholds_acceleration, double[] upper_torque_thresholds_acceleration, double[] lower_torque_thresholds_nominal, double[] upper_torque_thresholds_nominal, double[] lower_force_thresholds_acceleration, double[] upper_force_thresholds_acceleration, double[] lower_force_thresholds_nominal, double[] upper_force_thresholds_nominal)
        {
            this.lower_torque_thresholds_acceleration = lower_torque_thresholds_acceleration;
            this.upper_torque_thresholds_acceleration = upper_torque_thresholds_acceleration;
            this.lower_torque_thresholds_nominal = lower_torque_thresholds_nominal;
            this.upper_torque_thresholds_nominal = upper_torque_thresholds_nominal;
            this.lower_force_thresholds_acceleration = lower_force_thresholds_acceleration;
            this.upper_force_thresholds_acceleration = upper_force_thresholds_acceleration;
            this.lower_force_thresholds_nominal = lower_force_thresholds_nominal;
            this.upper_force_thresholds_nominal = upper_force_thresholds_nominal;
        }

        public static SetFullCollisionBehaviorRequest Deserialize(MessageDeserializer deserializer) => new SetFullCollisionBehaviorRequest(deserializer);

        private SetFullCollisionBehaviorRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lower_torque_thresholds_acceleration, sizeof(double), 7);
            deserializer.Read(out this.upper_torque_thresholds_acceleration, sizeof(double), 7);
            deserializer.Read(out this.lower_torque_thresholds_nominal, sizeof(double), 7);
            deserializer.Read(out this.upper_torque_thresholds_nominal, sizeof(double), 7);
            deserializer.Read(out this.lower_force_thresholds_acceleration, sizeof(double), 6);
            deserializer.Read(out this.upper_force_thresholds_acceleration, sizeof(double), 6);
            deserializer.Read(out this.lower_force_thresholds_nominal, sizeof(double), 6);
            deserializer.Read(out this.upper_force_thresholds_nominal, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lower_torque_thresholds_acceleration);
            serializer.Write(this.upper_torque_thresholds_acceleration);
            serializer.Write(this.lower_torque_thresholds_nominal);
            serializer.Write(this.upper_torque_thresholds_nominal);
            serializer.Write(this.lower_force_thresholds_acceleration);
            serializer.Write(this.upper_force_thresholds_acceleration);
            serializer.Write(this.lower_force_thresholds_nominal);
            serializer.Write(this.upper_force_thresholds_nominal);
        }

        public override string ToString()
        {
            return "SetFullCollisionBehaviorRequest: " +
            "\nlower_torque_thresholds_acceleration: " + System.String.Join(", ", lower_torque_thresholds_acceleration.ToList()) +
            "\nupper_torque_thresholds_acceleration: " + System.String.Join(", ", upper_torque_thresholds_acceleration.ToList()) +
            "\nlower_torque_thresholds_nominal: " + System.String.Join(", ", lower_torque_thresholds_nominal.ToList()) +
            "\nupper_torque_thresholds_nominal: " + System.String.Join(", ", upper_torque_thresholds_nominal.ToList()) +
            "\nlower_force_thresholds_acceleration: " + System.String.Join(", ", lower_force_thresholds_acceleration.ToList()) +
            "\nupper_force_thresholds_acceleration: " + System.String.Join(", ", upper_force_thresholds_acceleration.ToList()) +
            "\nlower_force_thresholds_nominal: " + System.String.Join(", ", lower_force_thresholds_nominal.ToList()) +
            "\nupper_force_thresholds_nominal: " + System.String.Join(", ", upper_force_thresholds_nominal.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
