//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetJointConfigurationRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetJointConfiguration";
        public override string RosMessageName => k_RosMessageName;

        public string[] joint_names;
        public double[] joint_positions;

        public SetJointConfigurationRequest()
        {
            this.joint_names = new string[0];
            this.joint_positions = new double[0];
        }

        public SetJointConfigurationRequest(string[] joint_names, double[] joint_positions)
        {
            this.joint_names = joint_names;
            this.joint_positions = joint_positions;
        }

        public static SetJointConfigurationRequest Deserialize(MessageDeserializer deserializer) => new SetJointConfigurationRequest(deserializer);

        private SetJointConfigurationRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.joint_positions, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.WriteLength(this.joint_positions);
            serializer.Write(this.joint_positions);
        }

        public override string ToString()
        {
            return "SetJointConfigurationRequest: " +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\njoint_positions: " + System.String.Join(", ", joint_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
