//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetKFrameRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetKFrame";
        public override string RosMessageName => k_RosMessageName;

        public double[] EE_T_K;

        public SetKFrameRequest()
        {
            this.EE_T_K = new double[16];
        }

        public SetKFrameRequest(double[] EE_T_K)
        {
            this.EE_T_K = EE_T_K;
        }

        public static SetKFrameRequest Deserialize(MessageDeserializer deserializer) => new SetKFrameRequest(deserializer);

        private SetKFrameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.EE_T_K, sizeof(double), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.EE_T_K);
        }

        public override string ToString()
        {
            return "SetKFrameRequest: " +
            "\nEE_T_K: " + System.String.Join(", ", EE_T_K.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
