//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetLoadRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetLoad";
        public override string RosMessageName => k_RosMessageName;

        public double mass;
        public double[] F_x_center_load;
        public double[] load_inertia;

        public SetLoadRequest()
        {
            this.mass = 0.0;
            this.F_x_center_load = new double[3];
            this.load_inertia = new double[9];
        }

        public SetLoadRequest(double mass, double[] F_x_center_load, double[] load_inertia)
        {
            this.mass = mass;
            this.F_x_center_load = F_x_center_load;
            this.load_inertia = load_inertia;
        }

        public static SetLoadRequest Deserialize(MessageDeserializer deserializer) => new SetLoadRequest(deserializer);

        private SetLoadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mass);
            deserializer.Read(out this.F_x_center_load, sizeof(double), 3);
            deserializer.Read(out this.load_inertia, sizeof(double), 9);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mass);
            serializer.Write(this.F_x_center_load);
            serializer.Write(this.load_inertia);
        }

        public override string ToString()
        {
            return "SetLoadRequest: " +
            "\nmass: " + mass.ToString() +
            "\nF_x_center_load: " + System.String.Join(", ", F_x_center_load.ToList()) +
            "\nload_inertia: " + System.String.Join(", ", load_inertia.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
